source 'http://ruby.taobao.org'

gem 'rails', '3.2.6'
gem 'jquery-rails'
gem 'mysql2'

# Bootstrap
gem "twitter-bootstrap-rails"

# 表单
gem 'simple_form'

# 注册/登录
gem 'devise'
#gem 'omniauth'

# 分页
gem 'kaminari'

gem 'carrierwave'
 
# 图表
#gem 'lazy_high_charts'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  gem 'therubyracer', :platforms => :ruby
  gem 'uglifier', '>= 1.0.3'
end

group :test, :development do
    gem 'rspec-rails', '~> 2.5'
end

group :test do
  gem 'cucumber-rails'
  gem 'capybara'
  gem 'database_cleaner'
end

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'
