require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RoomResourcesController do

  # This should return the minimal set of attributes required to create a valid
  # RoomResource. As you add validations to RoomResource, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RoomResourcesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all room_resources as @room_resources" do
      room_resource = RoomResource.create! valid_attributes
      get :index, {}, valid_session
      assigns(:room_resources).should eq([room_resource])
    end
  end

  describe "GET show" do
    it "assigns the requested room_resource as @room_resource" do
      room_resource = RoomResource.create! valid_attributes
      get :show, {:id => room_resource.to_param}, valid_session
      assigns(:room_resource).should eq(room_resource)
    end
  end

  describe "GET new" do
    it "assigns a new room_resource as @room_resource" do
      get :new, {}, valid_session
      assigns(:room_resource).should be_a_new(RoomResource)
    end
  end

  describe "GET edit" do
    it "assigns the requested room_resource as @room_resource" do
      room_resource = RoomResource.create! valid_attributes
      get :edit, {:id => room_resource.to_param}, valid_session
      assigns(:room_resource).should eq(room_resource)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new RoomResource" do
        expect {
          post :create, {:room_resource => valid_attributes}, valid_session
        }.to change(RoomResource, :count).by(1)
      end

      it "assigns a newly created room_resource as @room_resource" do
        post :create, {:room_resource => valid_attributes}, valid_session
        assigns(:room_resource).should be_a(RoomResource)
        assigns(:room_resource).should be_persisted
      end

      it "redirects to the created room_resource" do
        post :create, {:room_resource => valid_attributes}, valid_session
        response.should redirect_to(RoomResource.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved room_resource as @room_resource" do
        # Trigger the behavior that occurs when invalid params are submitted
        RoomResource.any_instance.stub(:save).and_return(false)
        post :create, {:room_resource => {}}, valid_session
        assigns(:room_resource).should be_a_new(RoomResource)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        RoomResource.any_instance.stub(:save).and_return(false)
        post :create, {:room_resource => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested room_resource" do
        room_resource = RoomResource.create! valid_attributes
        # Assuming there are no other room_resources in the database, this
        # specifies that the RoomResource created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        RoomResource.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => room_resource.to_param, :room_resource => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested room_resource as @room_resource" do
        room_resource = RoomResource.create! valid_attributes
        put :update, {:id => room_resource.to_param, :room_resource => valid_attributes}, valid_session
        assigns(:room_resource).should eq(room_resource)
      end

      it "redirects to the room_resource" do
        room_resource = RoomResource.create! valid_attributes
        put :update, {:id => room_resource.to_param, :room_resource => valid_attributes}, valid_session
        response.should redirect_to(room_resource)
      end
    end

    describe "with invalid params" do
      it "assigns the room_resource as @room_resource" do
        room_resource = RoomResource.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RoomResource.any_instance.stub(:save).and_return(false)
        put :update, {:id => room_resource.to_param, :room_resource => {}}, valid_session
        assigns(:room_resource).should eq(room_resource)
      end

      it "re-renders the 'edit' template" do
        room_resource = RoomResource.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RoomResource.any_instance.stub(:save).and_return(false)
        put :update, {:id => room_resource.to_param, :room_resource => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested room_resource" do
      room_resource = RoomResource.create! valid_attributes
      expect {
        delete :destroy, {:id => room_resource.to_param}, valid_session
      }.to change(RoomResource, :count).by(-1)
    end

    it "redirects to the room_resources list" do
      room_resource = RoomResource.create! valid_attributes
      delete :destroy, {:id => room_resource.to_param}, valid_session
      response.should redirect_to(room_resources_url)
    end
  end

end
