development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: canary_development
  pool: 5
  username: root
  password: root
  host: localhost

test: &test
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: canary_test
  pool: 5
  username: root
  password: root
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: canary_production
  pool: 5
  username: root
  password: root
  host: localhost
cucumber:
  <<: *test