development:
  adapter: postgresql
  encoding: unicode
  database: canary_development
  pool: 5
  username: postgres
  password: postgres

test: &test
  adapter: postgresql
  encoding: unicode
  database: canary_test
  pool: 5
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: canary_production
  pool: 5
  username: postgres
  password: postgres
cucumber:
  <<: *test